### ISSUE TITLE
Strange behaviour after second start

### ISSUE THREAD

**Issue by moshkalev** [sabihoshi/GenshinLyreMidiPlayer#6]
![image](https://user-images.githubusercontent.com/46562127/114734090-56e06d00-9d5d-11eb-8d12-a9f4232a0d64.png)
this is the error of not opening file.
I have another one, but it shows only one track 
![image](https://user-images.githubusercontent.com/46562127/114734457-a7f06100-9d5d-11eb-847b-439c481051cd.png)

**Comment by sabihoshi** [comment]
Just as a question, what is the name of the file? I think this error is happening because of it unable to find the file, or that your download is corrupted somehow. Because for me it is working so far, so I can only go with the differences we have.

If you try to ignore it and try playing the song, what happens?

**Comment by sabihoshi** [comment]
I made a new build sorry, it seems like pressing "Ignore" does nothing on that version, get it in here: https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v1.6.4.1

**Comment by moshkalev** [comment]
path: "C:\Users\Alchem\Downloads\Always_look_on_the_bright_side_of_life.mid"
Now it's opening, but all tracks are "unknown"
![image](https://user-images.githubusercontent.com/46562127/114765099-2fe66300-9d7e-11eb-8cca-1953d3d1933a.png)

**Comment by moshkalev** [comment]
[midi.zip](https://github.com/sabihoshi/GenshinLyreMidiPlayer/files/6313155/midi.zip)
Uploading files for testing. One with error and the second is with one track only.

**Comment by sabihoshi** [comment]
I've tested both and they seem to work fine if you make it ignore the error. The 2nd one works fine as intended, it really does only have one track.

As for names being "Unknown" that's because the person who made the MIDI file put no name in the MIDI track, so it defaults to unknown instead.

You can see that the 2nd file does only have one track as seen if you use a MIDI editor like https://www.midieditor.org/

**Comment by moshkalev** [comment]
OK, I opened other files and they're working fine.
I think issue is closed.
