### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by shadowxdgamer** [sabihoshi/GenshinLyreMidiPlayer#9]
Can you add a way to play songs with other people/players? duet songs or trios or even with 4 players?
a multiplayer mode

https://www.facebook.com/100002729674498/videos/3552013878232900/
here's a video that was done using your tool :d

Sorry i didnt mention you or the tool, the group has a rule about self promotion

**Comment by sabihoshi** [comment]
I'm not sure how that would be implemented, like it would be synced somehow? Then it would need online capabilities, which would need a server, or maybe some server to sync all of them, both of which is more complicated than what most people can do.

I think the easiest way you can do it is to record the audio separately, while the other player not really playing anything and then mixing both audio together, that would be the best way and have it be synced the best.

Even though it might not be a "live" duet, it still is a duet nonetheless, and doesn't come with the issue of having to perfectly time it together and start together.

Also, giving credit to the tool isn't self promotion, since you weren't the one who made it, self promotion only applies if you were the one who made it yourself, I think it would be fine if you credit me for it.

**Comment by shadowxdgamer** [comment]
hmm i was thinking of something like players connect to the host and then when he press play he sends input
if it's hard to implement that's ok (implementing stuff that requires the internet is a headache) it was just an idea after all.

im using an AHK script to check for windows time and send input when time is achieved

![image](https://user-images.githubusercontent.com/64868173/118068612-915c1a80-b39a-11eb-8c82-aee7241bea29.png)

And yeah i want this tool to thrive i will try my best to mention you and the tool, thanks and adiós
i will put a link to the tool next time

**Comment by sabihoshi** [comment]
If you do need a timer, having a loop on a script could be expensive, if you want, you can try the release [v1.10.0](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v1.10.0) I added a timer in the settings you can use to automatically play at a specific time.
